deploy:
  provider: releases
  api_key:
  file: foo/*
  on:
    repo: davidnewhall/motifini



# Powered by Application Builder: https://github.com/golift/application-builder
language: go
git:
  depth: false
# If your repo name is different than the binary name, you may need to set this.
# Either set this, or change the $GHPATH variable in .metadata.sh.
go_import_path: github.com/golift/hello-world
addons:
  apt:
    packages:
    - ruby-dev
    - rpm
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - zip
go:
  - 1.12.x
services:
  - docker
install:
  - mkdir -p $GOPATH/bin
  # Download the `dep` binary to bin folder in $GOPATH
  - curl -sLo $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v0.5.3/dep-linux-amd64
  - chmod +x $GOPATH/bin/dep
  # download super-linter: golangci-lint
  - curl -sL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - rvm install 2.0.0
  - rvm 2.0.0 do gem install --no-document fpm
before_script:
  # Create your own deploy key, tar it, and encrypt the file to make this work. Optionally add a bitly_token file to the archive.
    openssl aes-256-cbc -K $encrypted_ef062ca318f1_key -iv $encrypted_ef062ca318f1_iv -in .secret-files.tar.enc -out .secret-files.tar -d
  - tar -xf .secret-files.tar
  - source .metadata.sh
  - make vendor
script:
  # Test Go and Docker.
  - make test
  - make docker
  # Test built docker image.
  - docker run $BINARY -v 2>&1 | grep -Eq "^$BINARY v$VERSION"
  # Build everything
  - rvm 2.0.0 do make formula
after_success:
  # Display Release Folder
  - ls -l release/
  # Setup the ssh client so we can clone and push to the homebrew formula repo.
  # You must put github_deploy_file into .secret_files.tar.enc
  # This is an ssh key added to your homebrew forumla repo.
  - |
    mkdir -p $HOME/.ssh
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config
    [ ! -f github_deploy_key ] || (mv github_deploy_key $SSH_FILE \
      && chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
        "Host github.com" \
        "  IdentityFile $SSH_FILE" \
        "  StrictHostKeyChecking no" \
        "  LogLevel ERROR" >> $HOME/.ssh/config)
deploy:
  - provider: releases
    api_key:
      # to get a secure api key, run: travis setup releases
      # make a copy of this file first because that command will change it.
      secure: Y4uLKAzNn9QnRFRQGI6RP2n1uSa8gvaKSTZ4zVkf25bR2EZUVsF2BMZk1D01396uxxDU3ZxupEWcnh0Oe9jFNCa7Xo6RXyqwM3jyMWS7rqLPHkwVBBJdCQx0mPTp7Y3TFPf1iGqz2yfIQDZqRUGJFYAMh2svFjPQXtLgX/Po5RTT3XMd3gRUsx3ogEj7HCVg+aQeNY3mlKpzFAyfzsuOcByEjxYV3kW56E1Ku93dk80kSwG5KsZPbMn4u8Qvsts12W7BH3CHbdku2fmWAWy0KbuGFOuAebtg/38koQDmFVRkckqZMryEKiYETHFyl7vZsRYMVomLjrjspb2bQWvOUhS7nbJIjdPWLuInMu8HJvGUsMWVURi11VILmvJq0IKalfAeF46Nq+e+NlZW5MqwRJpBkLhZGw/dJk9f5T2S/x33xecSI5kVV3NsaaKJFP7gO6sr/PsQOcyQs0bYLMQnWiEI+TzSYWYixa9uEPo806w8cRP4lbYRW8jjxQ0AOZH7RqHYSbjEaMcoHx2gAcqeFlmVkvC7rHC3cCVatOXSRWKkEs/RUgYakWnJk3IchpzJLfQ4IMquzugMZDA0aSgHRW5FqxOddEysQT5cxjDQyh7NfY6nIkc3Jtm9tYuo6lbwDbk24x37KrH9UL+MT3o1of2yNKUgVEvVzbcl2IlS/JU=
    overwrite: true
    skip_cleanup: true
    file_glob: true
    file: release/*
    on:
      tags: true
  - provider: script
    script: scripts/formula-deploy.sh
    on:
      tags: true
